# Generated by Django 3.0.5 on 2020-10-01 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_purchasefromvendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Vendor'),
        ),
        migrations.AlterField(
            model_name='purchasefromvendor',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
