# Generated by Django 3.0.5 on 2020-10-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20201010_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='imageplaceholder.jpg', null=True, upload_to=''),
        ),
    ]
